/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'maperr' at '31/05/16 7:03 AM' with Gradle 2.13
 *
 * @author maperr, @date 31/05/16 7:03 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
